package studentrecord;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seej
 */
public class studRecordGUI extends javax.swing.JFrame {

    /**
     * Creates new form studRecordGUI
     */
    public studRecordGUI() {
        initComponents();
      
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (ClassNotFoundException e) {
            System.out.println("Where is your Oracle JDBC Driver?");
            e.printStackTrace();
            return;
        }
        System.out.println("Oracle JDBC Driver Registered!");
        Connection connection = null;
        try {
            connection = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ITESSPEC", "0123");
        } catch (SQLException e) {
            System.out.println("Connection Failed! Check output console");
            e.printStackTrace();
            return;
        }

        if (connection != null) {
            System.out.println("You made it, take control your database now!");
        } else {
            System.out.println("Failed to make connection!");
        }

        studRec_pane.setEnabledAt(0, true);
        studRec_pane.setEnabledAt(1, false);
        studRec_pane.setEnabledAt(2, false);
        studRec_pane.setEnabledAt(3, false);
        studRec_pane.setEnabledAt(4, false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        studRec_pane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        username_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        password_pf = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        viewRecords_lbl = new javax.swing.JLabel();
        srch_view_tf = new javax.swing.JTextField();
        srch_view_lbl = new javax.swing.JLabel();
        vwAlll_cb = new javax.swing.JCheckBox();
        ent_view_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        view_tbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_LBL = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        pane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lname_tf = new javax.swing.JTextField();
        fname_tf = new javax.swing.JTextField();
        lname_lbl = new javax.swing.JLabel();
        fname_lbl = new javax.swing.JLabel();
        bday_lbl = new javax.swing.JLabel();
        month_cmb = new javax.swing.JComboBox<>();
        day_cmb = new javax.swing.JComboBox<>();
        year_cmb = new javax.swing.JComboBox<>();
        age_lbl = new javax.swing.JLabel();
        age_tf = new javax.swing.JTextField();
        gender_lbl = new javax.swing.JLabel();
        gender_cmb = new javax.swing.JComboBox<>();
        program_lbl = new javax.swing.JLabel();
        program_cmb = new javax.swing.JComboBox<>();
        section_lbl = new javax.swing.JLabel();
        section_cmb = new javax.swing.JComboBox<>();
        ent_add_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        srch_edit_lbl = new javax.swing.JLabel();
        srch_edit_tf = new javax.swing.JTextField();
        lname_rb = new javax.swing.JRadioButton();
        fname_rb = new javax.swing.JRadioButton();
        bday_rb = new javax.swing.JRadioButton();
        age_rb = new javax.swing.JRadioButton();
        gender_rb = new javax.swing.JRadioButton();
        program_rb = new javax.swing.JRadioButton();
        section_rb = new javax.swing.JRadioButton();
        edit_lbl = new javax.swing.JLabel();
        ent_edit_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        edit_tbl = new javax.swing.JTable();
        new_val_upd_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        new_val_BTN = new javax.swing.JLabel();
        edit_BTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        srch_del_lbl = new javax.swing.JLabel();
        srch_del_tf = new javax.swing.JTextField();
        dall_cb = new javax.swing.JCheckBox();
        ent_del_btn = new javax.swing.JButton();
        del_lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username_lbl.setText("Username:");

        password_lbl.setText("Password:");

        username_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_tfActionPerformed(evt);
            }
        });

        login_btn.setText("LOGIN");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecord/new.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        jLabel2.setText("Student Record System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username_lbl)
                            .addComponent(password_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_tf)
                            .addComponent(password_pf)
                            .addComponent(login_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_lbl))
                .addGap(18, 18, 18)
                .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        studRec_pane.addTab("Login", jPanel1);

        viewRecords_lbl.setFont(new java.awt.Font("Andalus", 0, 20)); // NOI18N
        viewRecords_lbl.setText("View Records");

        srch_view_tf.setText("Enter I.D.");

        srch_view_lbl.setText("Search:");

        vwAlll_cb.setText("View All Students");
        vwAlll_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vwAlll_cbActionPerformed(evt);
            }
        });

        ent_view_btn.setText("ENTER");
        ent_view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ent_view_btnActionPerformed(evt);
            }
        });

        view_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "I.D.", "Last Name", "First Name", "Age", "Gender", "Birthdate"
            }
        ));
        jScrollPane2.setViewportView(view_tbl);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecord/copy.png"))); // NOI18N

        jLabel7.setText("Admin:");

        id_LBL.setForeground(new java.awt.Color(0, 102, 0));
        id_LBL.setText("    ");

        logout_btn.setText("Logout");
        logout_btn.setActionCommand("");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(srch_view_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewRecords_lbl)
                                    .addComponent(srch_view_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)
                                .addComponent(jLabel4)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(vwAlll_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ent_view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(id_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout_btn)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(viewRecords_lbl)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srch_view_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srch_view_lbl)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ent_view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vwAlll_cb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(id_LBL)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logout_btn)))
                .addContainerGap())
        );

        studRec_pane.addTab("View Record", jPanel2);

        jLabel3.setFont(new java.awt.Font("Andalus", 0, 20)); // NOI18N
        jLabel3.setText("Add Record");

        lname_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lname_tfActionPerformed(evt);
            }
        });

        fname_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_tfActionPerformed(evt);
            }
        });

        lname_lbl.setText("Last Name:");
        lname_lbl.setToolTipText("");

        fname_lbl.setText("First Name:");

        bday_lbl.setText("Birthdate:");

        month_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        day_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        year_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990" }));

        age_lbl.setText("Age:");

        gender_lbl.setText("Gender:");

        gender_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        program_lbl.setText("Program:");

        program_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS-SE", "CS-SMBA", "IT-AGD", "IT-DA", "IT-SMBA", "IT-WMA" }));

        section_lbl.setText("Section:");

        section_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1", "L2", "M1", "M2", "X1", "X2", "R1", "R2", "B1", "B2", "W1", "W2" }));

        ent_add_btn.setText("ENTER");
        ent_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ent_add_btnActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecord/copy.png"))); // NOI18N

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(ent_add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bday_lbl)
                            .addComponent(program_lbl))
                        .addGap(10, 10, 10)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(month_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(day_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(year_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(program_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(age_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(gender_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gender_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(section_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(section_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneLayout.createSequentialGroup()
                                .addComponent(lname_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(fname_lbl)))
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addContainerGap())))))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname_lbl)
                    .addComponent(fname_lbl))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bday_lbl)
                    .addComponent(month_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age_lbl)
                    .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender_lbl)
                    .addComponent(gender_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(program_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(program_lbl)
                    .addComponent(section_lbl)
                    .addComponent(section_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(ent_add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        studRec_pane.addTab("Add", pane);

        srch_edit_lbl.setText("Search:");

        srch_edit_tf.setText("Enter I.D");
        srch_edit_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_edit_tfActionPerformed(evt);
            }
        });

        buttonGroup1.add(lname_rb);
        lname_rb.setLabel("Last Name");

        buttonGroup1.add(fname_rb);
        fname_rb.setLabel("First Name");

        buttonGroup1.add(bday_rb);
        bday_rb.setText("Birthdate");

        buttonGroup1.add(age_rb);
        age_rb.setText("Age");

        buttonGroup1.add(gender_rb);
        gender_rb.setText("Gender");

        buttonGroup1.add(program_rb);
        program_rb.setText("Program");

        buttonGroup1.add(section_rb);
        section_rb.setText("Section");

        edit_lbl.setFont(new java.awt.Font("Andalus", 0, 20)); // NOI18N
        edit_lbl.setText("Edit Record");

        ent_edit_btn.setText("OK");
        ent_edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ent_edit_btnActionPerformed(evt);
            }
        });

        edit_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "I.D.", "Last Name", "First Name", "Age", "Gender", "Birthdate"
            }
        ));
        jScrollPane3.setViewportView(edit_tbl);

        new_val_upd_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_val_upd_TFActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecord/copy.png"))); // NOI18N

        new_val_BTN.setText("Enter new value:");

        edit_BTN.setText("EDIT");
        edit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(srch_edit_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(srch_edit_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(edit_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lname_rb)
                        .addGap(18, 18, 18)
                        .addComponent(fname_rb)
                        .addGap(17, 17, 17)
                        .addComponent(bday_rb)
                        .addGap(18, 18, 18)
                        .addComponent(age_rb))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(new_val_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(new_val_upd_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ent_edit_btn)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(gender_rb)
                        .addGap(18, 18, 18)
                        .addComponent(program_rb)))
                .addGap(18, 18, 18)
                .addComponent(section_rb)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(edit_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srch_edit_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srch_edit_lbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname_rb)
                    .addComponent(fname_rb)
                    .addComponent(bday_rb)
                    .addComponent(age_rb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_rb)
                    .addComponent(program_rb)
                    .addComponent(section_rb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ent_edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_val_upd_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_val_BTN)
                    .addComponent(edit_BTN))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        studRec_pane.addTab("Edit", jPanel4);

        srch_del_lbl.setText("Search:");

        srch_del_tf.setText("Enter I.D.");

        dall_cb.setText("Delete All");
        dall_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dall_cbActionPerformed(evt);
            }
        });

        ent_del_btn.setText("ENTER");
        ent_del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ent_del_btnActionPerformed(evt);
            }
        });

        del_lbl.setFont(new java.awt.Font("Andalus", 0, 20)); // NOI18N
        del_lbl.setText("Delete Record");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentrecord/copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 125, Short.MAX_VALUE)
                        .addComponent(srch_del_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(srch_del_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(dall_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(del_lbl)
                            .addComponent(ent_del_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(114, 114, 114)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(del_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srch_del_lbl)
                    .addComponent(srch_del_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dall_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ent_del_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        studRec_pane.addTab("Delete", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studRec_pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studRec_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        Statement stm = null;
        String username = null;
        String password = null;
        String id = null;
        ResultSet rs = null;
        Connection connection = null;


        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "ITESSPEC", "0123");
            connection.setAutoCommit(true);
            stm = connection.createStatement();
            rs = stm.executeQuery("SELECT * FROM admin WHERE admin_name = '" +  username_tf.getText() + "' AND admin_password = '" + password_pf.getText()+ "'");

            while(rs.next()) {
                username = rs.getString("admin_name");
                password = rs.getString("admin_password");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        if(username != null && password != null) {
            id_LBL.setText(username);
            JOptionPane.showMessageDialog(this, "Account successfuly logged in!");
            studRec_pane.setSelectedIndex(studRec_pane.getSelectedIndex()+1);
            studRec_pane.setEnabledAt(0, false);
            studRec_pane.setEnabledAt(1, true);
            studRec_pane.setEnabledAt(2, true);
            studRec_pane.setEnabledAt(3, true);
            studRec_pane.setEnabledAt(4, true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Login not successful. Please try again");
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void vwAlll_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vwAlll_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vwAlll_cbActionPerformed

    private void lname_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lname_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfActionPerformed

    private void fname_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_tfActionPerformed

    private void dall_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dall_cbActionPerformed

    }//GEN-LAST:event_dall_cbActionPerformed

    private void ent_del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_del_btnActionPerformed
        // Kulang:
        
        String search = srch_del_tf.getText();
        if(srch_del_tf.getText().equals("Enter I.D.") && !dall_cb.isSelected()) {
            JOptionPane.showMessageDialog(this, "INVALID I.D. \nPlease try again.", "Message", JOptionPane.PLAIN_MESSAGE);
        } 
        else if (srch_del_tf.getText().equals("")){
            JOptionPane.showMessageDialog(this, "INVALID I.D. \nPlease try again.", "Message", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            if (dall_cb.isSelected()) {
                int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete all records? ");
                if(choice == 0) {
                    try {
                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                        Statement s = connection.createStatement();
                        String sql = "DELETE FROM Student";
                        s.executeUpdate(sql);
                        s.executeUpdate("commit");
                        connection.setAutoCommit(true);
                        s.close();
                        connection.close();
                        JOptionPane.showMessageDialog(this, "All records deleted", "Message", JOptionPane.CLOSED_OPTION);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
            else {
                try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                    Statement s = connection.createStatement();
                    String sql = "DELETE FROM student WHERE stud_id = " + "'" + search + "'";
                    s.executeUpdate(sql);
                    connection.setAutoCommit(true);
                    s.close();
                    connection.close();
                    JOptionPane.showMessageDialog(this, "Record deleted", "Message", JOptionPane.PLAIN_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_ent_del_btnActionPerformed

    private void srch_edit_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_edit_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_edit_tfActionPerformed

    private void ent_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_add_btnActionPerformed
        String bday = month_cmb.getSelectedItem().toString() + "-" + day_cmb.getSelectedItem().toString() + "-" + year_cmb.getSelectedItem().toString();
        
        int prog_id = 0, sec_id = 0;
            if(program_cmb.getSelectedItem().toString().equals("CS-SE")) {
                prog_id = 1004;
            }
            else if(program_cmb.getSelectedItem().toString().equals("CS-SMBA")) {
                prog_id = 1005;
            }
            else if(program_cmb.getSelectedItem().toString().equals("IT-AGD")) {
                prog_id = 1002;
            }
            else if(program_cmb.getSelectedItem().toString().equals("IT-DA")) {
                prog_id = 1001;
            }
            else if(program_cmb.getSelectedItem().toString().equals("IT-SMBA")) {
                prog_id = 1000;
            }
            else if(program_cmb.getSelectedItem().toString().equals("IT-WMA")) {
                prog_id = 1003;
            }
            
            if (section_cmb.getSelectedItem().toString().equals("L1")){
                sec_id = 18;
            }
            else if (section_cmb.getSelectedItem().toString().equals("L2")){
                sec_id = 19;
            }
            else if (section_cmb.getSelectedItem().toString().equals("M1")){
                sec_id = 20;
            }
            else if (section_cmb.getSelectedItem().toString().equals("M2")){
                sec_id = 21;
            }
            else if (section_cmb.getSelectedItem().toString().equals("X1")){
                sec_id = 14;
            }
            else if (section_cmb.getSelectedItem().toString().equals("X2")){
                sec_id = 15;
            }
            else if (section_cmb.getSelectedItem().toString().equals("R1")){
                sec_id = 12;
            }
            else if (section_cmb.getSelectedItem().toString().equals("R2")){
                sec_id = 13;
            }
            else if (section_cmb.getSelectedItem().toString().equals("B1")){
                sec_id = 10;
            }
            else if (section_cmb.getSelectedItem().toString().equals("B2")){
                sec_id = 11;
            }
            else if (section_cmb.getSelectedItem().toString().equals("W1")){
                sec_id = 16;
            }
            else if (section_cmb.getSelectedItem().toString().equals("W2")){
                sec_id = 17;
            }
            
        try {         
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
            PreparedStatement ps = connection.prepareStatement("INSERT INTO STUDENT VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, null);
            ps.setString(2, fname_tf.getText());
            ps.setString(3, lname_tf.getText());
            ps.setInt(4, Integer.parseInt(age_tf.getText()));
            ps.setString(5, gender_cmb.getSelectedItem().toString());
            ps.setString(6, bday);
            ps.setInt(7, prog_id);
            ps.setInt(8, sec_id);

            ps.executeUpdate();
            connection.setAutoCommit(true);
            connection.close();
            JOptionPane.showMessageDialog(this, "1 row inserted", "Message", JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ent_add_btnActionPerformed

    private void new_val_upd_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_val_upd_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_val_upd_TFActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
            studRec_pane.setSelectedIndex(studRec_pane.getSelectedIndex()-1);
            studRec_pane.setEnabledAt(0, true);
            studRec_pane.setEnabledAt(1, false);
            studRec_pane.setEnabledAt(2, false);
            studRec_pane.setEnabledAt(3, false);
            studRec_pane.setEnabledAt(4, false);
            username_tf.setText("");
            password_pf.setText("");
            JOptionPane.showMessageDialog(this, "Logout successful.");
            
            srch_view_tf.setText("");
            lname_tf.setText("");
            fname_tf.setText("");
            age_tf.setText("");
            srch_edit_tf.setText("");
            new_val_upd_TF.setText("");
            srch_del_tf.setText("");
    }//GEN-LAST:event_logout_btnActionPerformed

    private void ent_edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_edit_btnActionPerformed
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null; 
        String id = srch_edit_tf.getText();
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
            con.setAutoCommit(true);
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM student WHERE stud_id = " + id);
            DefaultTableModel model = (DefaultTableModel) edit_tbl.getModel();
            model.setRowCount(0);
            while(rs.next()) {
                model.addRow(new Object[] {rs.getString(1), rs.getString(3), rs.getString(2), rs.getString(4), rs.getString(5), rs.getString(6)} );
            }    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_ent_edit_btnActionPerformed

    private void edit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_BTNActionPerformed
        if(lname_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                // create our java preparedstatement using a sql update query
//                Statement s = conn.createStatement();
//                ResultSet rs = s.executeQuery("SELECT * FROM STUDENT WHERE stud_id = " + new_val_upd_TF.getText());
//                if(rs.next()){
                    PreparedStatement ps = conn.prepareStatement("UPDATE student SET stud_lname = ? WHERE stud_id = ?");
                    // set the preparedstatement parameters
                    ps.setString(1, new_val_upd_TF.getText());
                    ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                    // call executeUpdate to execute our sql update statement
                    ps.executeUpdate();
                    ps.close();
                    conn.setAutoCommit(true);
                    JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
//                }
//                else {
//                    JOptionPane.showMessageDialog(null, "Student does not exist.", "Message", JOptionPane.CLOSED_OPTION);
//                }
                
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(fname_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                PreparedStatement ps = conn.prepareStatement("UPDATE student SET stud_fname = ? WHERE stud_id = ?");
                ps.setString(1, new_val_upd_TF.getText());
                ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                ps.executeUpdate();
                conn.setAutoCommit(true);
                ps.close();
                JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(bday_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                PreparedStatement ps = conn.prepareStatement("UPDATE student SET birthdate = ? WHERE stud_id = ?");
                ps.setString(1, new_val_upd_TF.getText());
                ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                ps.executeUpdate();
                conn.setAutoCommit(true);
                ps.close();
                JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(age_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                PreparedStatement ps = conn.prepareStatement("UPDATE student SET age = ? WHERE stud_id = ?");
                ps.setString(1, new_val_upd_TF.getText());
                ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                ps.executeUpdate();
                conn.setAutoCommit(true);
                ps.close();
                JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(age_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                PreparedStatement ps = conn.prepareStatement("UPDATE student SET age = ? WHERE stud_id = ?");
                ps.setString(1, new_val_upd_TF.getText());
                ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                ps.executeUpdate();
                conn.setAutoCommit(true);
                ps.close();
                JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(gender_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                PreparedStatement ps = conn.prepareStatement("UPDATE student SET gender = ? WHERE stud_id = ?");
                ps.setString(1, new_val_upd_TF.getText());
                ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                ps.executeUpdate();
                conn.setAutoCommit(true);
                ps.close();
                JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(program_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                PreparedStatement ps = conn.prepareStatement("UPDATE student SET PROGRAM_PROG_ID = ? WHERE stud_id = ?");
                ps.setString(1, new_val_upd_TF.getText());
                ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                ps.executeUpdate();
                conn.setAutoCommit(true);
                ps.close();
                JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(section_rb.isSelected()){
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                PreparedStatement ps = conn.prepareStatement("UPDATE student SET SECTION_SECTION_ID = ? WHERE stud_id = ?");
                ps.setString(1, new_val_upd_TF.getText());
                ps.setInt(2, Integer.parseInt(srch_edit_tf.getText()));
                ps.executeUpdate();
                conn.setAutoCommit(true);
                ps.close();
                JOptionPane.showMessageDialog(this, "Edit successful. \n1 row modified.", "Message", JOptionPane.CLOSED_OPTION);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_edit_BTNActionPerformed

    private void ent_view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ent_view_btnActionPerformed
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;    
        String id = srch_view_tf.getText();
        
        if(srch_view_tf.getText().equals("Enter I.D.") && !vwAlll_cb.isSelected()) {
            JOptionPane.showMessageDialog(this, "INVALID I.D. \nPlease try again.", "Message", JOptionPane.PLAIN_MESSAGE);
        } 
        else if (srch_view_tf.getText().equals("") && !vwAlll_cb.isSelected()){
            JOptionPane.showMessageDialog(this, "INVALID I.D. \nPlease try again.", "Message", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            if (vwAlll_cb.isSelected()) {
                try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                    con.setAutoCommit(true);
                    stmt = con.createStatement();
                    rs = stmt.executeQuery("SELECT * FROM student");
                    DefaultTableModel model = (DefaultTableModel)view_tbl.getModel();
                    model.setRowCount(0);
                    while(rs.next()){
                        model.addRow(new Object[] {rs.getString(1), rs.getString(3), rs.getString(2), rs.getString(4), rs.getString(5), rs.getString(6)} );
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                } 
            }
            else {
                try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ITESSPEC", "0123");
                    con.setAutoCommit(true);
                    stmt = con.createStatement();
                    rs = stmt.executeQuery("SELECT * FROM student WHERE stud_id = " + id);
                    DefaultTableModel model = (DefaultTableModel)view_tbl.getModel();
                    model.setRowCount(0);
                    while(rs.next()){
                        model.addRow(new Object[] {rs.getString(1), rs.getString(3), rs.getString(2), rs.getString(4), rs.getString(5), rs.getString(6)} );
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                } 
            }
        }
    }//GEN-LAST:event_ent_view_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studRecordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studRecordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age_lbl;
    private javax.swing.JRadioButton age_rb;
    private javax.swing.JTextField age_tf;
    private javax.swing.JLabel bday_lbl;
    private javax.swing.JRadioButton bday_rb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox dall_cb;
    private javax.swing.JComboBox<String> day_cmb;
    private javax.swing.JLabel del_lbl;
    private javax.swing.JButton edit_BTN;
    private javax.swing.JLabel edit_lbl;
    private javax.swing.JTable edit_tbl;
    private javax.swing.JButton ent_add_btn;
    private javax.swing.JButton ent_del_btn;
    private javax.swing.JButton ent_edit_btn;
    private javax.swing.JButton ent_view_btn;
    private javax.swing.JLabel fname_lbl;
    private javax.swing.JRadioButton fname_rb;
    private javax.swing.JTextField fname_tf;
    private javax.swing.JComboBox<String> gender_cmb;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JRadioButton gender_rb;
    private javax.swing.JLabel id_LBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lname_lbl;
    private javax.swing.JRadioButton lname_rb;
    private javax.swing.JTextField lname_tf;
    private javax.swing.JButton login_btn;
    private javax.swing.JButton logout_btn;
    private javax.swing.JComboBox<String> month_cmb;
    private javax.swing.JLabel new_val_BTN;
    private javax.swing.JTextField new_val_upd_TF;
    private javax.swing.JPanel pane;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_pf;
    private javax.swing.JComboBox<String> program_cmb;
    private javax.swing.JLabel program_lbl;
    private javax.swing.JRadioButton program_rb;
    private javax.swing.JComboBox<String> section_cmb;
    private javax.swing.JLabel section_lbl;
    private javax.swing.JRadioButton section_rb;
    private javax.swing.JLabel srch_del_lbl;
    private javax.swing.JTextField srch_del_tf;
    private javax.swing.JLabel srch_edit_lbl;
    private javax.swing.JTextField srch_edit_tf;
    private javax.swing.JLabel srch_view_lbl;
    private javax.swing.JTextField srch_view_tf;
    private javax.swing.JTabbedPane studRec_pane;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_tf;
    private javax.swing.JLabel viewRecords_lbl;
    private javax.swing.JTable view_tbl;
    private javax.swing.JCheckBox vwAlll_cb;
    private javax.swing.JComboBox<String> year_cmb;
    // End of variables declaration//GEN-END:variables
}